### ISSUE TITLE
Program algorithm

### ISSUE THREAD

**Issue by jlrzarcor** [optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-jlrzarcor#2]
- [x] Implementar el método numérico seleccionado en Python para resolver problemas de optimización convexa de pequeña escala.
- [x] Seleccionar los ejemplos para los tests.

**Comment by jlrzarcor** [comment]
Sprint Review:

En sesión del pasado martes 23 de marzo 2021, se decide modificar el algoritmo a programar, de CVaR a regresión logística debido a las condiciones críticas de tiempo que experimentó el equipo.

**Comment by lgarayva** [comment]
Ya están funcionando la paquetería, faltaría publicar el paquete en línea, será conveniente ya cerrar este issue?

**Comment by jlrzarcor** [comment]
Adelante con el cierre de este issue.
