### ISSUE TITLE
Dockering

### ISSUE THREAD

**Issue by jlrzarcor** [optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-jlrzarcor#4]
- [x] Crear Dockerfile y colocarlo en este repo.
- [x] Construir imagen de docker que instale todo el software necesario para que funcione el paquete. 
- [x] Actualizar el contenedor de docker mediante github actions.
- [x] Instalar en el contenedor el paquete trabajado por el equipo de programación.
 
> -  **Nota**: esta imágen debe construirse y alojarse (**_Build & Push_**) automáticamente en dockerhub con un lanzamiento de un workflow de github vía github actions. De esta forma, cualquier commit que modifique el Dockerfile debe lanzar un worfklow de github que dispare un **_build & push_** al dockerhub de manera automática.

**Comment by jlrzarcor** [comment]
@lgarayva , Leo, porque no intentas con este código:

RUN apt-get update && apt-get install -y pip3 install --upgrade pip

**Comment by lgarayva** [comment]
Sí tenemos esa instrucción más arriba en el Dockerfile, voy a ver si es un error de lectura del mismo

**Comment by jlrzarcor** [comment]
@lgarayva , de acuerdo con la documentación README del Docker File, muy ilustrativa.

**Comment by lgarayva** [comment]
Ya quedó listo el contenedor, se incorporó el paquete hecho por el equipo de programación y pasa las pruebas de github actions.
