### ISSUE TITLE
Test algorithm

### ISSUE THREAD

**Issue by jlrzarcor** [optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-jlrzarcor#5]
- [x] Crear el **_Autograding_**. Los tests deben pasar automáticamente con un lanzamiento de un _workflow_ de _github_ vía _github actions_.
- [x] Elaborar los Tests de pequeña escala que revisan que el método numérico resuelve correctamente dos problemas de optimización convexa.

**Comment by lgarayva** [comment]
Ya se crearon test de los paquetes, estoy en espera a que el equipo de programación suba las demás funciones.

**Comment by Carlosrlpzi** [comment]
Revise lo test y me parece que todo corre bien. Por mí está bien que ya se cierre este issue

**Comment by Lobolc** [comment]
Todo súper bien, procede a cerrar el issue.

**Comment by lgarayva** [comment]
De acuerdo, procedo a cerrar el issue.
