### ISSUE TITLE
Document and Publicate

### ISSUE THREAD

**Issue by jlrzarcor** [optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-jlrzarcor#6]
**_Project manager_**.

- [x] Crear documentación del paquete con sphinx.
- [x] Publicar la documentación con _github pages_ o _readthedocs_.
- [x] Elaborar un botón de **_binder_** para que desde este repo se pueda probar el paquete.

**Comment by jlrzarcor** [comment]
@Lobolc @Carlosrlpzi ; ¿creo que el cirterio de paro que más favorece es el de norma de la función por la estructura del problema de CVaR, cómo ven?

**Comment by jlrzarcor** [comment]
@Lobolc , muy bien Mike, me parece que está funcionando bien en local. En cuanto puedas nos reunimos para ver que no vaya a "crashear" en el GirHub.

**Comment by jlrzarcor** [comment]
Sprint Review & Debrief @26/03/2021:

Actualmente estamos trabajando en los siguientes puntos para finalizar el proyecto:

1. Equipo de Programación, @Carlosrlpzi está realizando la documentación de los módulos de python que resuleven el problema de optimización.
2. Equipo docker&test, @Carlosrlpzi; actualmente se ha revisado y validado que el Autograde y Build&Push están funcionando adecuadamente. Una vez terminado Programming será integrado el paquete y el código final para los test.
3. Equipo Docmentar. @Lobolc @jlrzarcor . Actualmente se está colaborando en el desarrollo de la documentación en Sphinx.

Siguientes pasos:
Finalizar la publicacion con git-hub pages una vez terminados los puntos anteriores.

**Comment by lgarayva** [comment]
@jlrzarcor cómo va el tema de la documentación?

**Comment by jlrzarcor** [comment]
Se realiza cambio de carpetas para mantener el html requerido. Debido a una inconsistencia en el archivo index se perdió la configuración correcta.

**Comment by Carlosrlpzi** [comment]
Adelante con el cierre.

**Comment by jlrzarcor** [comment]
Se cierra este issue.
